server.port: 8089

server.resource.path: http://localhost:8088/

#hystrix.command.default.execution.timeout.enabled=false


#
#feign:
#  client:
#    config:
#      feignName:
#        connectTimeout: 5000
#        readTimeout: 5000
#        loggerLevel: full
#        errorDecoder: com.example.SimpleErrorDecoder
#        retryer: com.example.SimpleRetryer
#        requestInterceptors:
#          - com.example.FooRequestInterceptor
#          - com.example.BarRequestInterceptor
#        decode404: false
#
##
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 4000
#NAME.ribbon.ReadTimeout: 8000

#hystrix.command."SyncBlockClient#getPerson(Integer)".execution.is‌​olation.thread.timeo‌​utInMilliseconds= 2000
