server:
    port: 13003
spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/spring_database_tranaction?characterEncoding=UTF-8&useSSL=false&createDatabaseIfNotExist=true
        username: root
        password:
        tomcat:
            test-on-borrow: true
            validation-query: SELECT 1
            max-active: 50
            max-idle: 20
            min-idle: 15
            initial-size: 1
    jpa:
        hibernate:
            ddl-auto: none
            dialect: org.hibernate.dialect.MySQLDialect
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            format_sql: true
liquibase:
    changeLog: "classpath:db/changelog/master.xml"
logging:
    level:
        com.hibernate.demo: DEBUG
        org.hibernate.SQL: DEBUG