server.port: 8443
security.require-ssl: true
server.ssl.key-store: classpath:keystore.p12
server.ssl.key-store-password: 123456
server.ssl.keyStoreType: JKS
#server.ssl.keyStoreType: PKCS12
server.ssl.key-store-provider: SUN
server.ssl.keyAlias: moheqionglin

ssl.soap.username: mohe_soap_user
ssl.soap:password: 123456#

server.nonssl.port: 8080